Traceback (most recent call last):
  File "d:\python_projects\raspisanie2\main.py", line 82, in start
    script_3(file_name=excel_table, key_word=key_word, output_table=f'{output}/raspisanie.xlsx')
  File "d:\python_projects\raspisanie2\scripts.py", line 44, in script_3
    group = get_group(del_spaces(ws1._get_cell(row=cell.row-1-offset[time], column=cell.column).value))
KeyError: 'заведующаяучебнойчастьюЕ.Е.Автономова'
